### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by msadowski** [LuSeKa/HoverBot#3]
Hi!

I'm covering this project for the next issue of [Weekly Robotics](https://weeklyrobotics.com/). I couldn't find any information about the project's licence and AFAIK this makes the "all rights reserved" the default in theory forbidding others from reproducing your work.

Thanks for sharing this project!

**Comment by LuSeKa** [comment]
Hi Mateusz,

thanks for pointing this out, I added a standard MIT license file.
I am excited that you are planning ot cover HoverBot in Weekly Robotics, I highly appreciate it!

**Comment by msadowski** [comment]
Thanks! That's helpful! Here is the WR issue that features HoverBot: https://weeklyrobotics.com/weekly-robotics-45 in case you are interested :)

**Comment by LuSeKa** [comment]
Awesome, thank you! I added the link to WR#45 to the press section of the HoverBot readme: https://github.com/LuSeKa/HoverBot/blob/master/README.md#press
