### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by sylajen** [LuSeKa/HoverBot#4]
Hey there,

We're using this code in a similar fashion for a 2 wheeled self balancing robot, however we ran into some issues with the compiler. We're trying to use the Hoverbot.ino file, however when we try to run the code, a series of errors have come up, with the error in the image below being the one issue we have been having the most trouble with. Just wanted to see if this is an error you've had yourself or if you are familiar with how to resolve this. Thanks.

![error](https://user-images.githubusercontent.com/33578533/140435569-5d956566-0245-47d3-b14d-f98ed39c978a.png)

**Comment by CrispyFungus** [comment]
I did get past this, I will have to get back to you

**Comment by sylajen** [comment]
Sounds good, if possible, would you be willing to do a call so we can explain the situation and show it in greater detail? Please let me know, you can email me at nothinggistrue@gmail.com.

**Comment by CrispyFungus** [comment]
Yes some time this weekend I could be available, this is what I did with
the code, it may be similar to what you're doing.

https://youtu.be/iIDN5WiU3wc

**Comment by sylajen** [comment]
What time would you be available tomorrow and your preferred method of contact? I live in the Eastern Time zone

**Comment by CrispyFungus** [comment]
Did you try using the Adafruit BNO055 sketch they have on their website? I didn't copy the hoverbot code verbatim. Also do you have the motor drivers in close proximity to the BNO055? Are you using other I2C devices? Did you check that the address pre programmed on the BNO055 is matching your sketch?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CrispyFungus** [comment]
If you'd Like, I can send my Segway sketch I made and then you try, I used the ODrive as well

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sylajen** [comment]
Yes please the Segway sketch would be very helpful. We are also having troubles with recharging the battery with an iMAX B6 balance charger, where it says check cell, low voltage and won't charge the battery. We were wondering if this was an issue you ran into, or if it was something you know how to resolve?

**Comment by CrispyFungus** [comment]
My battery I custom built, there's 2 battery packs, I use a LUNA brand
charger and an integrated BMS in the pack to make sure that the cells are
balanced. As far as charging a lithium pack with a balance plug make sure
thst the battery isn't below 3.2V/cell. Probe ground to each pin on the
balance plug, the 1st shoukd be ~3.7v, the next 7.4, 11.1, and so on in
multiples of the first cell's voltage. If it is not, then you have a
problem with the battery and the charger shouldn't charge it otherwise
there could be fire.

**Comment by sylajen** [comment]
We have the ODrive 3.6v, whereas it seems you guys have the ODrive 3.2v. Our ODrive supplies a voltage of 3.3V, whereas it seems yours had one that supplied 5V. Just wondering if that's something that would cause an issue?

**Comment by CrispyFungus** [comment]
Yeah if your bno055 requires 5v then yes it wouldn't turn on. Explains why
when connected via usb you can see the imu.

**Comment by sylajen** [comment]
Do you know any places we would be able to purchase this specific ODrive? Or if there's some chance you'd be willing to sell yours?

**Comment by CrispyFungus** [comment]
I actually happen to have a brand new spare never used, I'll probably never
use it so I can sell it to you. I'll sell it $125 including shipping if you
live in the US. My venmo is @JasonWason

**Comment by sylajen** [comment]
I will have to let you know about the purchase some time soon. We are curious though as to why you are drawing 5V from the ODrive and passing it to the breadboard with the IMU, ODrive and Receiver? Is it used for feedback somehow, or simply to power those components?

**Comment by CrispyFungus** [comment]
My circuits are custom and are by no means similar to the hoverbot, the
Odrive has a 1A 5v bus to power other devices, it makes it simpler, along
with the serial communication more reliable to be both powered and grounded
to the Odrive. All peripheral devices such as lighting and sound on my
project are powered by a separate 5v BEC regulator, but still switched on
and off using a MOSFET controlled by devices from the 5v bus

**Comment by LuSeKa** [comment]
@sylajen looking at the commit log of ODriveArduino, [this ](https://github.com/odriverobotics/ODrive/commit/e59ee5cda129397f95d4e1938ebc2fd83e5af9ee#diff-73a2e762cab92d6303c3004c7a173035d503082880019366e4bbc42f49cb9090)is the commit that is causing the compiler error that you are seeing. There are multiple ways to work around this. The easiest is probably to replace the line that's causing (line 107 in HoverBot.ino) it with 
`int requested state = AXIS_STATE_IDLE`
There might be more places where this needs to be changed. It looks like ODriveArduino has changed quite a bit, so maybe there are more changes that broke compatibility with HoverBot. Another option to work around all of them is to use the version of ODriveArduino of the time of the last HoverBot commit (3 years ago).

**Comment by LuSeKa** [comment]
Fixed in commit [598a4f9bca46923243acd8985dc611be21acde3f](https://github.com/LuSeKa/HoverBot/commit/598a4f9bca46923243acd8985dc611be21acde3f). Thanks for flagging this!
@sylajen you can just pull the latest version of HoverBot and this issue should be gone.
